spring.application.name=billing-system
server.port=8080

# Database - H2 (in-memory for development)
#spring.datasource.url=jdbc:h2:mem:billingdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## JPA/Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=false


#jdbc:postgresql://db.sjkhhekjnopxnrfpyzao.supabase.co:5432/postgres?user=postgres&password=Supabase@8599

# Database - MySQL
#spring.datasource.url=jdbc:postgresql://db.sjkhhekjnopxnrfpyzao.supabase.co:5432/postgres?user=postgres&password=Supabase@8599
#spring.datasource.username=postgres
#spring.datasource.password=Supabase@8599

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


spring.jpa.properties.hibernate.default_schema=shinde_agencies


spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false


## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JWT Configuration
jwt.secret=MyVerySecureSecretKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmChangeThis
jwt.expiration=3600000

# CORS
#spring.webmvc.cors.allowed-origins=http://localhost:3000,http://localhost:3001
spring.webmvc.cors.allowed-origins=${UI_ORIGIN}
spring.webmvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# HikariCP - REQUIRED for Supabase free tier
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

# Avoid prepared statement collisions
spring.jpa.properties.hibernate.statement_cache.size=0
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
